### ISSUE TITLE
Utiliser la même version de zmarkdown que zds-site

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/ansible-zestedesavoir#21]
Actuellement, il y a deux soucis : 

- on utilise une version de pm2 installée globalement, ce qui fait qu'elle n'est pas mise à jour au fur et à mesure ;
- on installe zmarkdown avec un `package.json` utilisé dans ce dépôt au lieu d'utiliser celui de `zds-site`.

Il faut : 

- supprimer ce bout de code
  https://github.com/zestedesavoir/ansible-zestedesavoir/blob/b23a84a6b0c1c061d54a5618f5415ea5c73a486b/roles/zmd/tasks/main.yml#L7-L12
- remplacer `/usr/lib/node_modules/pm2/bin/pm2` par `/opt/zmd/node_modules/pm2/bin/pm2` dans `roles/zmd/templates/zmd.service.j2`
- supprimer `roles/zmd/templates/package.json.j2`
- remplacer ceci par cela : 
  https://github.com/zestedesavoir/ansible-zestedesavoir/blob/b23a84a6b0c1c061d54a5618f5415ea5c73a486b/roles/zmd/tasks/main.yml#L24-L32
  ```
  - name: copy server package.json
    copy:
      src: "{{ appdir }}/zmd/package.json"
      dest: /opt/zmd/package.json
    register: zmd_package
    notify: restart zmd
    tags:
      - bootstrap
      - upgrade
  ```
